# Generated by Django 5.2.4 on 2025-07-23 23:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("isbn", models.CharField(db_index=True, max_length=20)),
            ],
            options={
                "db_table": "book",
            },
        ),
        migrations.CreateModel(
            name="BookStock",
            fields=[
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stock",
                        serialize=False,
                        to="books.book",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "book_stock",
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                django.db.models.functions.text.Lower("title"),
                name="idx_book_title_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="idx_book_isbn"),
        ),
    ]
